####
POST http://127.0.0.1:8099/v0/user
Content-Type: application/json

{
  "name": "wangwu123",
  "password": "wangwu123123"
}



#### Get user by id
GET http://127.0.0.1:8099/v0/user/id/1


#### Get user by id
GET http://127.0.0.1:8099/v0/user/name/wangwu123
