
### create post
POST http://127.0.0.1:8099/v0/post
Content-Type: application/json
AuthorName: wangwu123

{
    "title": "这是我的第一篇 blog",
    "content":"大家好， 这是我的第一篇 blog"
}


### read post
GET http://127.0.0.1:8099/v0/post/id/1
Content-Type: application/json